### ISSUE TITLE
Catch slow USB controller data corruption 

### ISSUE THREAD

**Issue by samkristoff** [Digilent/waveforms-live#65]
Catch data corruption due to slow USB controller on host computer and stop acquisition.  Link to FAQ or white paper with detail and troubleshooting suggestions.

**Comment by PhantomMachine** [comment]
Added a modal that displays when corrupted data is encountered, both for the oscilloscope and logic analyzer read methods. The modal details why the issue is occurring and how to fix it. A link to the FAQ is provided for further information, and a link to the Forums is given for technical support.

Changes to the Digilent Instrumentation Protocol were made to bubble up a 'corrupt transfer' error, that is then caught by the application and triggers the display of the described modal.

commit: 7513bc1
